interface Districts {
  districtId: number;
  districtName: string;
  stateName: string;
  stateId: number;
}

const districts: Districts[] = [
  {
    districtId: 582,
    districtName: 'Adilabad',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 320,
    districtName: 'Agar',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 796,
    districtName: 'Agatti Island',
    stateName: 'Lakshadweep',
    stateId: 19,
  },
  {
    districtId: 622,
    districtName: 'Agra',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 154,
    districtName: 'Ahmedabad',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 770,
    districtName: 'Ahmedabad Corporation',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 391,
    districtName: 'Ahmednagar',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 425,
    districtName: 'Aizawl East',
    stateName: 'Mizoram',
    stateId: 24,
  },
  {
    districtId: 426,
    districtName: 'Aizawl West',
    stateName: 'Mizoram',
    stateId: 24,
  },
  {
    districtId: 507,
    districtName: 'Ajmer',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 364,
    districtName: 'Akola',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 301,
    districtName: 'Alappuzha',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 623,
    districtName: 'Aligarh',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 710,
    districtName: 'Alipurduar District',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 357,
    districtName: 'Alirajpur',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 704,
    districtName: 'Almora',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 512,
    districtName: 'Alwar',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 193,
    districtName: 'Ambala',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 625,
    districtName: 'Ambedkar Nagar',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 626,
    districtName: 'Amethi',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 366,
    districtName: 'Amravati',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 174,
    districtName: 'Amreli',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 485,
    districtName: 'Amritsar',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 627,
    districtName: 'Amroha',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 179,
    districtName: 'Anand',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 9,
    districtName: 'Anantapur',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 224,
    districtName: 'Anantnag',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 445,
    districtName: 'Angul',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 22,
    districtName: 'Anjaw',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 334,
    districtName: 'Anuppur',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 779,
    districtName: 'Aranthangi',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 74,
    districtName: 'Araria',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 158,
    districtName: 'Aravalli',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 555,
    districtName: 'Ariyalur',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 78,
    districtName: 'Arwal',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 354,
    districtName: 'Ashoknagar',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 578,
    districtName: 'Attur',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 628,
    districtName: 'Auraiya',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 77,
    districtName: 'Aurangabad',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 397,
    districtName: 'Aurangabad ',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 646,
    districtName: 'Ayodhya',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 629,
    districtName: 'Azamgarh',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 630,
    districtName: 'Badaun',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 270,
    districtName: 'Bagalkot',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 707,
    districtName: 'Bageshwar',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 631,
    districtName: 'Baghpat',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 632,
    districtName: 'Bahraich',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 46,
    districtName: 'Baksa',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 338,
    districtName: 'Balaghat',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 448,
    districtName: 'Balangir',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 633,
    districtName: 'Balarampur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 447,
    districtName: 'Balasore',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 634,
    districtName: 'Ballia',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 110,
    districtName: 'Balod',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 111,
    districtName: 'Baloda bazar',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 112,
    districtName: 'Balrampur',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 159,
    districtName: 'Banaskantha',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 635,
    districtName: 'Banda',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 223,
    districtName: 'Bandipore',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 276,
    districtName: 'Bangalore Rural',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 265,
    districtName: 'Bangalore Urban',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 83,
    districtName: 'Banka',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 711,
    districtName: 'Bankura',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 519,
    districtName: 'Banswara',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 636,
    districtName: 'Barabanki',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 225,
    districtName: 'Baramulla',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 516,
    districtName: 'Baran',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 637,
    districtName: 'Bareilly',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 472,
    districtName: 'Bargarh',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 528,
    districtName: 'Barmer',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 483,
    districtName: 'Barnala',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 47,
    districtName: 'Barpeta',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 343,
    districtName: 'Barwani',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 712,
    districtName: 'Basirhat HD (North 24 Parganas)',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 113,
    districtName: 'Bastar',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 638,
    districtName: 'Basti',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 493,
    districtName: 'Bathinda',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 294,
    districtName: 'BBMP',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 384,
    districtName: 'Beed',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 98,
    districtName: 'Begusarai',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 264,
    districtName: 'Belgaum',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 274,
    districtName: 'Bellary',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 114,
    districtName: 'Bemetara',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 362,
    districtName: 'Betul',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 687,
    districtName: 'Bhadohi',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 583,
    districtName: 'Bhadradri Kothagudem',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 454,
    districtName: 'Bhadrak',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 82,
    districtName: 'Bhagalpur',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 370,
    districtName: 'Bhandara',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 508,
    districtName: 'Bharatpur',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 180,
    districtName: 'Bharuch',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 175,
    districtName: 'Bhavnagar',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 771,
    districtName: 'Bhavnagar Corporation',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 523,
    districtName: 'Bhilwara',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 351,
    districtName: 'Bhind',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 200,
    districtName: 'Bhiwani',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 99,
    districtName: 'Bhojpur',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 312,
    districtName: 'Bhopal',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 272,
    districtName: 'Bidar',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 115,
    districtName: 'Bijapur',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 639,
    districtName: 'Bijnour',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 501,
    districtName: 'Bikaner',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 116,
    districtName: 'Bilaspur',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 219,
    districtName: 'Bilaspur',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 713,
    districtName: 'Birbhum',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 398,
    districtName: 'Bishnupur',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 714,
    districtName: 'Bishnupur HD (Bankura)',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 765,
    districtName: 'Biswanath',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 242,
    districtName: 'Bokaro',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 57,
    districtName: 'Bongaigaon',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 176,
    districtName: 'Botad',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 468,
    districtName: 'Boudh',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 229,
    districtName: 'Budgam',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 640,
    districtName: 'Bulandshahr',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 367,
    districtName: 'Buldhana',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 514,
    districtName: 'Bundi',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 342,
    districtName: 'Burhanpur',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 100,
    districtName: 'Buxar',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 66,
    districtName: 'Cachar',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 141,
    districtName: 'Central Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 271,
    districtName: 'Chamarajanagar',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 214,
    districtName: 'Chamba',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 699,
    districtName: 'Chamoli',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 708,
    districtName: 'Champawat',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 429,
    districtName: 'Champhai',
    stateName: 'Mizoram',
    stateId: 24,
  },
  {
    districtId: 641,
    districtName: 'Chandauli',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 399,
    districtName: 'Chandel',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 108,
    districtName: 'Chandigarh',
    stateName: 'Chandigarh',
    stateId: 6,
  },
  {
    districtId: 380,
    districtName: 'Chandrapur',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 20,
    districtName: 'Changlang',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 766,
    districtName: 'Charaideo',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 201,
    districtName: 'Charkhi Dadri',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 245,
    districtName: 'Chatra',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 565,
    districtName: 'Chengalpet',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 571,
    districtName: 'Chennai',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 778,
    districtName: 'Cheyyar',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 328,
    districtName: 'Chhatarpur',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 337,
    districtName: 'Chhindwara',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 181,
    districtName: 'Chhotaudepur',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 273,
    districtName: 'Chikamagalur',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 291,
    districtName: 'Chikkaballapur',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 58,
    districtName: 'Chirang',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 268,
    districtName: 'Chitradurga',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 642,
    districtName: 'Chitrakoot',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 10,
    districtName: 'Chittoor',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 521,
    districtName: 'Chittorgarh',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 400,
    districtName: 'Churachandpur',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 530,
    districtName: 'Churu',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 539,
    districtName: 'Coimbatore',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 715,
    districtName: 'Cooch Behar',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 783,
    districtName: 'COOCHBEHAR',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 547,
    districtName: 'Cuddalore',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 457,
    districtName: 'Cuttack',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 137,
    districtName: 'Dadra and Nagar Haveli',
    stateName: 'Dadra and Nagar Haveli',
    stateId: 8,
  },
  {
    districtId: 182,
    districtName: 'Dahod',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 716,
    districtName: 'Dakshin Dinajpur',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 269,
    districtName: 'Dakshina Kannada',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 138,
    districtName: 'Daman',
    stateName: 'Daman and Diu',
    stateId: 37,
  },
  {
    districtId: 327,
    districtName: 'Damoh',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 163,
    districtName: 'Dang',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 117,
    districtName: 'Dantewada',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 94,
    districtName: 'Darbhanga',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 717,
    districtName: 'Darjeeling',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 48,
    districtName: 'Darrang',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 350,
    districtName: 'Datia',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 511,
    districtName: 'Dausa',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 275,
    districtName: 'Davanagere',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 697,
    districtName: 'Dehradun',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 473,
    districtName: 'Deogarh',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 253,
    districtName: 'Deoghar',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 643,
    districtName: 'Deoria',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 168,
    districtName: 'Devbhumi Dwaraka',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 324,
    districtName: 'Dewas',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 614,
    districtName: 'Dhalai',
    stateName: 'Tripura',
    stateId: 33,
  },
  {
    districtId: 118,
    districtName: 'Dhamtari',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 257,
    districtName: 'Dhanbad',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 341,
    districtName: 'Dhar',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 566,
    districtName: 'Dharmapuri',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 278,
    districtName: 'Dharwad',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 62,
    districtName: 'Dhemaji',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 458,
    districtName: 'Dhenkanal',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 524,
    districtName: 'Dholpur',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 59,
    districtName: 'Dhubri',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 388,
    districtName: 'Dhule',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 718,
    districtName: 'Diamond Harbor HD (S 24 Parganas)',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 25,
    districtName: 'Dibang Valley',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 43,
    districtName: 'Dibrugarh',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 67,
    districtName: 'Dima Hasao',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 434,
    districtName: 'Dimapur',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 556,
    districtName: 'Dindigul',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 336,
    districtName: 'Dindori',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 139,
    districtName: 'Diu',
    stateName: 'Daman and Diu',
    stateId: 37,
  },
  {
    districtId: 232,
    districtName: 'Doda',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 258,
    districtName: 'Dumka',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 520,
    districtName: 'Dungarpur',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 119,
    districtName: 'Durg',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 719,
    districtName: 'East Bardhaman',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 105,
    districtName: 'East Champaran',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 145,
    districtName: 'East Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 424,
    districtName: 'East Garo Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 11,
    districtName: 'East Godavari',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 418,
    districtName: 'East Jaintia Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 23,
    districtName: 'East Kameng',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 414,
    districtName: 'East Khasi Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 42,
    districtName: 'East Siang',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 535,
    districtName: 'East Sikkim',
    stateName: 'Sikkim',
    stateId: 30,
  },
  {
    districtId: 247,
    districtName: 'East Singhbhum',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 307,
    districtName: 'Ernakulam',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 563,
    districtName: 'Erode',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 644,
    districtName: 'Etah',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 645,
    districtName: 'Etawah',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 199,
    districtName: 'Faridabad',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 499,
    districtName: 'Faridkot',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 647,
    districtName: 'Farrukhabad',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 196,
    districtName: 'Fatehabad',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 484,
    districtName: 'Fatehgarh Sahib',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 648,
    districtName: 'Fatehpur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 487,
    districtName: 'Fazilka',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 480,
    districtName: 'Ferozpur',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 649,
    districtName: 'Firozabad',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 280,
    districtName: 'Gadag',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 379,
    districtName: 'Gadchiroli',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 467,
    districtName: 'Gajapati',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 228,
    districtName: 'Ganderbal',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 153,
    districtName: 'Gandhinagar',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 772,
    districtName: 'Gandhinagar Corporation',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 449,
    districtName: 'Ganjam',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 243,
    districtName: 'Garhwa',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 120,
    districtName: 'Gariaband',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 136,
    districtName: 'Gaurela Pendra Marwahi ',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 650,
    districtName: 'Gautam Buddha Nagar',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 79,
    districtName: 'Gaya',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 651,
    districtName: 'Ghaziabad',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 652,
    districtName: 'Ghazipur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 177,
    districtName: 'Gir Somnath',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 256,
    districtName: 'Giridih',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 60,
    districtName: 'Goalpara',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 262,
    districtName: 'Godda',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 53,
    districtName: 'Golaghat',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 615,
    districtName: 'Gomati',
    stateName: 'Tripura',
    stateId: 33,
  },
  {
    districtId: 653,
    districtName: 'Gonda',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 378,
    districtName: 'Gondia',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 104,
    districtName: 'Gopalganj',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 654,
    districtName: 'Gorakhpur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 267,
    districtName: 'Gulbarga',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 251,
    districtName: 'Gumla',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 348,
    districtName: 'Guna',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 5,
    districtName: 'Guntur',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 489,
    districtName: 'Gurdaspur',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 188,
    districtName: 'Gurgaon',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 313,
    districtName: 'Gwalior',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 68,
    districtName: 'Hailakandi',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 217,
    districtName: 'Hamirpur',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 655,
    districtName: 'Hamirpur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 517,
    districtName: 'Hanumangarh',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 656,
    districtName: 'Hapur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 361,
    districtName: 'Harda',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 657,
    districtName: 'Hardoi',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 702,
    districtName: 'Haridwar',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 289,
    districtName: 'Hassan',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 658,
    districtName: 'Hathras',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 279,
    districtName: 'Haveri',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 255,
    districtName: 'Hazaribagh',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 386,
    districtName: 'Hingoli',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 191,
    districtName: 'Hisar',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 764,
    districtName: 'Hojai',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 720,
    districtName: 'Hoogly',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 360,
    districtName: 'Hoshangabad',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 481,
    districtName: 'Hoshiarpur',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 721,
    districtName: 'Howrah',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 581,
    districtName: 'Hyderabad',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 306,
    districtName: 'Idukki',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 401,
    districtName: 'Imphal East',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 402,
    districtName: 'Imphal West',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 314,
    districtName: 'Indore',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 17,
    districtName: 'Itanagar Capital Complex',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 315,
    districtName: 'Jabalpur',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 459,
    districtName: 'Jagatsinghpur',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 584,
    districtName: 'Jagtial',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 505,
    districtName: 'Jaipur I',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 506,
    districtName: 'Jaipur II',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 527,
    districtName: 'Jaisalmer',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 460,
    districtName: 'Jajpur',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 492,
    districtName: 'Jalandhar',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 659,
    districtName: 'Jalaun',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 390,
    districtName: 'Jalgaon',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 396,
    districtName: 'Jalna',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 533,
    districtName: 'Jalore',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 722,
    districtName: 'Jalpaiguri',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 230,
    districtName: 'Jammu',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 169,
    districtName: 'Jamnagar',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 773,
    districtName: 'Jamnagar Corporation',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 259,
    districtName: 'Jamtara',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 107,
    districtName: 'Jamui',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 585,
    districtName: 'Jangaon',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 121,
    districtName: 'Janjgir-Champa',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 122,
    districtName: 'Jashpur',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 660,
    districtName: 'Jaunpur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 586,
    districtName: 'Jayashankar Bhupalpally',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 91,
    districtName: 'Jehanabad',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 340,
    districtName: 'Jhabua',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 189,
    districtName: 'Jhajjar',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 515,
    districtName: 'Jhalawar',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 661,
    districtName: 'Jhansi',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 723,
    districtName: 'Jhargram',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 474,
    districtName: 'Jharsuguda',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 510,
    districtName: 'Jhunjhunu',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 204,
    districtName: 'Jind',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 410,
    districtName: 'Jiribam',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 502,
    districtName: 'Jodhpur',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 587,
    districtName: 'Jogulamba Gadwal',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 54,
    districtName: 'Jorhat',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 178,
    districtName: 'Junagadh',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 774,
    districtName: 'Junagadh Corporation',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 80,
    districtName: 'Kaimur',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 190,
    districtName: 'Kaithal',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 413,
    districtName: 'Kakching',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 464,
    districtName: 'Kalahandi',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 724,
    districtName: 'Kalimpong',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 552,
    districtName: 'Kallakurichi',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 588,
    districtName: 'Kamareddy',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 409,
    districtName: 'Kamjong',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 24,
    districtName: 'Kamle',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 49,
    districtName: 'Kamrup Metropolitan',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 50,
    districtName: 'Kamrup Rural',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 557,
    districtName: 'Kanchipuram',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 450,
    districtName: 'Kandhamal',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 408,
    districtName: 'Kangpokpi',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 213,
    districtName: 'Kangra',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 123,
    districtName: 'Kanker',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 662,
    districtName: 'Kannauj',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 297,
    districtName: 'Kannur',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 663,
    districtName: 'Kanpur Dehat',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 664,
    districtName: 'Kanpur Nagar',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 544,
    districtName: 'Kanyakumari',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 479,
    districtName: 'Kapurthala',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 476,
    districtName: 'Karaikal',
    stateName: 'Puducherry',
    stateId: 27,
  },
  {
    districtId: 525,
    districtName: 'Karauli',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 51,
    districtName: 'Karbi-Anglong',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 309,
    districtName: 'Kargil',
    stateName: 'Ladakh',
    stateId: 18,
  },
  {
    districtId: 69,
    districtName: 'Karimganj',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 589,
    districtName: 'Karimnagar',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 203,
    districtName: 'Karnal',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 559,
    districtName: 'Karur',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 295,
    districtName: 'Kasaragod',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 665,
    districtName: 'Kasganj',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 234,
    districtName: 'Kathua',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 75,
    districtName: 'Katihar',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 353,
    districtName: 'Katni',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 666,
    districtName: 'Kaushambi',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 135,
    districtName: 'Kawardha',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 461,
    districtName: 'Kendrapara',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 455,
    districtName: 'Kendujhar',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 101,
    districtName: 'Khagaria',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 590,
    districtName: 'Khammam',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 339,
    districtName: 'Khandwa',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 344,
    districtName: 'Khargone',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 156,
    districtName: 'Kheda',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 616,
    districtName: 'Khowai',
    stateName: 'Tripura',
    stateId: 33,
  },
  {
    districtId: 252,
    districtName: 'Khunti',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 446,
    districtName: 'Khurda',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 216,
    districtName: 'Kinnaur',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 444,
    districtName: 'Kiphire',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 76,
    districtName: 'Kishanganj',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 231,
    districtName: 'Kishtwar',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 283,
    districtName: 'Kodagu',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 241,
    districtName: 'Koderma',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 441,
    districtName: 'Kohima',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 61,
    districtName: 'Kokrajhar',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 277,
    districtName: 'Kolar',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 428,
    districtName: 'Kolasib',
    stateName: 'Mizoram',
    stateId: 24,
  },
  {
    districtId: 371,
    districtName: 'Kolhapur',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 725,
    districtName: 'Kolkata',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 298,
    districtName: 'Kollam',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 124,
    districtName: 'Kondagaon',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 282,
    districtName: 'Koppal',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 451,
    districtName: 'Koraput',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 125,
    districtName: 'Korba',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 126,
    districtName: 'Koriya',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 503,
    districtName: 'Kota',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 304,
    districtName: 'Kottayam',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 780,
    districtName: 'Kovilpatti',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 305,
    districtName: 'Kozhikode',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 27,
    districtName: 'Kra Daadi',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 4,
    districtName: 'Krishna',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 562,
    districtName: 'Krishnagiri',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 221,
    districtName: 'Kulgam',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 211,
    districtName: 'Kullu',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 591,
    districtName: 'Kumuram Bheem',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 226,
    districtName: 'Kupwara',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 7,
    districtName: 'Kurnool',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 186,
    districtName: 'Kurukshetra',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 21,
    districtName: 'Kurung Kumey',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 667,
    districtName: 'Kushinagar',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 170,
    districtName: 'Kutch',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 210,
    districtName: 'Lahaul Spiti',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 63,
    districtName: 'Lakhimpur',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 668,
    districtName: 'Lakhimpur Kheri',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 84,
    districtName: 'Lakhisarai',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 311,
    districtName: 'Lakshadweep',
    stateName: 'Lakshadweep',
    stateId: 19,
  },
  {
    districtId: 669,
    districtName: 'Lalitpur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 244,
    districtName: 'Latehar',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 383,
    districtName: 'Latur',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 432,
    districtName: 'Lawngtlai',
    stateName: 'Mizoram',
    stateId: 24,
  },
  {
    districtId: 310,
    districtName: 'Leh',
    stateName: 'Ladakh',
    stateId: 18,
  },
  {
    districtId: 33,
    districtName: 'Lepa Rada',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 250,
    districtName: 'Lohardaga',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 29,
    districtName: 'Lohit',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 40,
    districtName: 'Longding',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 438,
    districtName: 'Longleng',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 31,
    districtName: 'Lower Dibang Valley',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 18,
    districtName: 'Lower Siang',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 32,
    districtName: 'Lower Subansiri',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 670,
    districtName: 'Lucknow',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 488,
    districtName: 'Ludhiana',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 431,
    districtName: 'Lunglei',
    stateName: 'Mizoram',
    stateId: 24,
  },
  {
    districtId: 70,
    districtName: 'Madhepura',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 95,
    districtName: 'Madhubani',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 540,
    districtName: 'Madurai',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 592,
    districtName: 'Mahabubabad',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 593,
    districtName: 'Mahabubnagar',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 671,
    districtName: 'Maharajganj',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 127,
    districtName: 'Mahasamund',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 477,
    districtName: 'Mahe',
    stateName: 'Puducherry',
    stateId: 27,
  },
  {
    districtId: 206,
    districtName: 'Mahendragarh',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 183,
    districtName: 'Mahisagar',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 672,
    districtName: 'Mahoba',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 673,
    districtName: 'Mainpuri',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 767,
    districtName: 'Majuli',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 302,
    districtName: 'Malappuram',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 726,
    districtName: 'Malda',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 469,
    districtName: 'Malkangiri',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 427,
    districtName: 'Mamit',
    stateName: 'Mizoram',
    stateId: 24,
  },
  {
    districtId: 594,
    districtName: 'Mancherial',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 215,
    districtName: 'Mandi',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 335,
    districtName: 'Mandla',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 319,
    districtName: 'Mandsaur',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 290,
    districtName: 'Mandya',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 482,
    districtName: 'Mansa',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 674,
    districtName: 'Mathura',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 675,
    districtName: 'Mau',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 456,
    districtName: 'Mayurbhanj',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 595,
    districtName: 'Medak',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 596,
    districtName: 'Medchal',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 676,
    districtName: 'Meerut',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 160,
    districtName: 'Mehsana',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 677,
    districtName: 'Mirzapur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 491,
    districtName: 'Moga',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 437,
    districtName: 'Mokokchung',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 439,
    districtName: 'Mon',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 678,
    districtName: 'Moradabad',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 171,
    districtName: 'Morbi',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 347,
    districtName: 'Morena',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 55,
    districtName: 'Morigaon',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 612,
    districtName: 'Mulugu',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 395,
    districtName: 'Mumbai',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 128,
    districtName: 'Mungeli',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 85,
    districtName: 'Munger',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 727,
    districtName: 'Murshidabad',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 679,
    districtName: 'Muzaffarnagar',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 86,
    districtName: 'Muzaffarpur',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 266,
    districtName: 'Mysore',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 470,
    districtName: 'Nabarangpur',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 728,
    districtName: 'Nadia',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 56,
    districtName: 'Nagaon',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 576,
    districtName: 'Nagapattinam',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 597,
    districtName: 'Nagarkurnool',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 532,
    districtName: 'Nagaur',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 365,
    districtName: 'Nagpur',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 709,
    districtName: 'Nainital',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 90,
    districtName: 'Nalanda',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 52,
    districtName: 'Nalbari',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 598,
    districtName: 'Nalgonda',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 558,
    districtName: 'Namakkal',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 36,
    districtName: 'Namsai',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 382,
    districtName: 'Nanded',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 729,
    districtName: 'Nandigram HD (East Medinipore)',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 387,
    districtName: 'Nandurbar',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 613,
    districtName: 'Narayanpet',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 129,
    districtName: 'Narayanpur',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 184,
    districtName: 'Narmada',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 352,
    districtName: 'Narsinghpur',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 389,
    districtName: 'Nashik',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 164,
    districtName: 'Navsari',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 92,
    districtName: 'Nawada',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 462,
    districtName: 'Nayagarh',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 323,
    districtName: 'Neemuch',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 140,
    districtName: 'New Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 3,
    districtName: 'Nicobar',
    stateName: 'Andaman and Nicobar Islands',
    stateId: 1,
  },
  {
    districtId: 577,
    districtName: 'Nilgiris',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 599,
    districtName: 'Nirmal',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 600,
    districtName: 'Nizamabad',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 412,
    districtName: 'Noney',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 730,
    districtName: 'North 24 Parganas',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 1,
    districtName: 'North and Middle Andaman',
    stateName: 'Andaman and Nicobar Islands',
    stateId: 1,
  },
  {
    districtId: 146,
    districtName: 'North Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 147,
    districtName: 'North East Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 423,
    districtName: 'North Garo Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 151,
    districtName: 'North Goa',
    stateName: 'Goa',
    stateId: 10,
  },
  {
    districtId: 537,
    districtName: 'North Sikkim',
    stateName: 'Sikkim',
    stateId: 30,
  },
  {
    districtId: 617,
    districtName: 'North Tripura',
    stateName: 'Tripura',
    stateId: 33,
  },
  {
    districtId: 143,
    districtName: 'North West Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 465,
    districtName: 'Nuapada',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 205,
    districtName: 'Nuh',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 381,
    districtName: 'Osmanabad',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 19,
    districtName: 'Pakke Kessang',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 261,
    districtName: 'Pakur',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 308,
    districtName: 'Palakkad',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 246,
    districtName: 'Palamu',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 564,
    districtName: 'Palani',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 394,
    districtName: 'Palghar',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 529,
    districtName: 'Pali',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 207,
    districtName: 'Palwal',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 187,
    districtName: 'Panchkula',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 185,
    districtName: 'Panchmahal',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 195,
    districtName: 'Panipat',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 326,
    districtName: 'Panna',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 39,
    districtName: 'Papum Pare',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 573,
    districtName: 'Paramakudi',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 385,
    districtName: 'Parbhani',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 731,
    districtName: 'Paschim Medinipore',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 161,
    districtName: 'Patan',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 300,
    districtName: 'Pathanamthitta',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 486,
    districtName: 'Pathankot',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 494,
    districtName: 'Patiala',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 97,
    districtName: 'Patna',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 698,
    districtName: 'Pauri Garhwal',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 601,
    districtName: 'Peddapalli',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 570,
    districtName: 'Perambalur',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 435,
    districtName: 'Peren',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 443,
    districtName: 'Phek',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 411,
    districtName: 'Pherzawl',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 680,
    districtName: 'Pilibhit',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 706,
    districtName: 'Pithoragarh',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 575,
    districtName: 'Poonamallee',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 238,
    districtName: 'Poonch',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 172,
    districtName: 'Porbandar',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 12,
    districtName: 'Prakasam',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 522,
    districtName: 'Pratapgarh',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 682,
    districtName: 'Pratapgarh',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 624,
    districtName: 'Prayagraj',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 475,
    districtName: 'Puducherry',
    stateName: 'Puducherry',
    stateId: 27,
  },
  {
    districtId: 546,
    districtName: 'Pudukkottai',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 227,
    districtName: 'Pulwama',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 363,
    districtName: 'Pune',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 732,
    districtName: 'Purba Medinipore',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 463,
    districtName: 'Puri',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 73,
    districtName: 'Purnia',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 733,
    districtName: 'Purulia',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 681,
    districtName: 'Raebareli',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 284,
    districtName: 'Raichur',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 393,
    districtName: 'Raigad',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 130,
    districtName: 'Raigarh',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 109,
    districtName: 'Raipur',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 359,
    districtName: 'Raisen',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 602,
    districtName: 'Rajanna Sircilla',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 358,
    districtName: 'Rajgarh',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 173,
    districtName: 'Rajkot',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 775,
    districtName: 'Rajkot Corporation',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 131,
    districtName: 'Rajnandgaon',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 237,
    districtName: 'Rajouri',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 518,
    districtName: 'Rajsamand',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 292,
    districtName: 'Ramanagara',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 567,
    districtName: 'Ramanathapuram',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 235,
    districtName: 'Ramban',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 254,
    districtName: 'Ramgarh',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 683,
    districtName: 'Rampur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 734,
    districtName: 'Rampurhat HD (Birbhum)',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 240,
    districtName: 'Ranchi',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 603,
    districtName: 'Rangareddy',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 781,
    districtName: 'Ranipet',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 322,
    districtName: 'Ratlam',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 372,
    districtName: 'Ratnagiri',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 471,
    districtName: 'Rayagada',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 239,
    districtName: 'Reasi',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 316,
    districtName: 'Rewa',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 202,
    districtName: 'Rewari',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 417,
    districtName: 'Ri-Bhoi',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 192,
    districtName: 'Rohtak',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 81,
    districtName: 'Rohtas',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 700,
    districtName: 'Rudraprayag',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 497,
    districtName: 'Rup Nagar',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 162,
    districtName: 'Sabarkantha',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 317,
    districtName: 'Sagar',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 684,
    districtName: 'Saharanpur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 71,
    districtName: 'Saharsa',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 260,
    districtName: 'Sahebganj',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 545,
    districtName: 'Salem',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 96,
    districtName: 'Samastipur',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 236,
    districtName: 'Samba',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 452,
    districtName: 'Sambalpur',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 685,
    districtName: 'Sambhal',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 604,
    districtName: 'Sangareddy',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 373,
    districtName: 'Sangli',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 498,
    districtName: 'Sangrur',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 686,
    districtName: 'Sant Kabir Nagar',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 102,
    districtName: 'Saran',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 496,
    districtName: 'SAS Nagar',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 376,
    districtName: 'Satara',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 333,
    districtName: 'Satna',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 534,
    districtName: 'Sawai Madhopur',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 500,
    districtName: 'SBS Nagar',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 356,
    districtName: 'Sehore',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 403,
    districtName: 'Senapati',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 349,
    districtName: 'Seoni',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 618,
    districtName: 'Sepahijala',
    stateName: 'Tripura',
    stateId: 33,
  },
  {
    districtId: 248,
    districtName: 'Seraikela Kharsawan',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 430,
    districtName: 'Serchhip',
    stateName: 'Mizoram',
    stateId: 24,
  },
  {
    districtId: 148,
    districtName: 'Shahdara',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 332,
    districtName: 'Shahdol',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 688,
    districtName: 'Shahjahanpur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 321,
    districtName: 'Shajapur',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 689,
    districtName: 'Shamli',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 93,
    districtName: 'Sheikhpura',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 87,
    districtName: 'Sheohar',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 346,
    districtName: 'Sheopur',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 35,
    districtName: 'Shi Yomi',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 208,
    districtName: 'Shimla',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 287,
    districtName: 'Shimoga',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 345,
    districtName: 'Shivpuri',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 222,
    districtName: 'Shopian',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 690,
    districtName: 'Shravasti',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 433,
    districtName: 'Siaha',
    stateName: 'Mizoram',
    stateId: 24,
  },
  {
    districtId: 37,
    districtName: 'Siang',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 691,
    districtName: 'Siddharthnagar',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 605,
    districtName: 'Siddipet',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 331,
    districtName: 'Sidhi',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 513,
    districtName: 'Sikar',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 249,
    districtName: 'Simdega',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 374,
    districtName: 'Sindhudurg',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 330,
    districtName: 'Singrauli',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 212,
    districtName: 'Sirmaur',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 531,
    districtName: 'Sirohi',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 194,
    districtName: 'Sirsa',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 88,
    districtName: 'Sitamarhi',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 692,
    districtName: 'Sitapur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 561,
    districtName: 'Sivaganga',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 580,
    districtName: 'Sivakasi',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 44,
    districtName: 'Sivasagar',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 103,
    districtName: 'Siwan',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 209,
    districtName: 'Solan',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 375,
    districtName: 'Solapur',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 693,
    districtName: 'Sonbhadra',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 198,
    districtName: 'Sonipat',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 64,
    districtName: 'Sonitpur',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 735,
    districtName: 'South 24 Parganas',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 2,
    districtName: 'South Andaman',
    stateName: 'Andaman and Nicobar Islands',
    stateId: 1,
  },
  {
    districtId: 149,
    districtName: 'South Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 144,
    districtName: 'South East Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 421,
    districtName: 'South Garo Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 152,
    districtName: 'South Goa',
    stateName: 'Goa',
    stateId: 10,
  },
  {
    districtId: 768,
    districtName: 'South Salmara Mankachar',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 538,
    districtName: 'South Sikkim',
    stateName: 'Sikkim',
    stateId: 30,
  },
  {
    districtId: 619,
    districtName: 'South Tripura',
    stateName: 'Tripura',
    stateId: 33,
  },
  {
    districtId: 150,
    districtName: 'South West Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 422,
    districtName: 'South West Garo Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 415,
    districtName: 'South West Khasi Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 509,
    districtName: 'Sri Ganganagar',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 490,
    districtName: 'Sri Muktsar Sahib',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 13,
    districtName: 'Sri Potti Sriramulu Nellore',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 14,
    districtName: 'Srikakulam',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 220,
    districtName: 'Srinagar',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 466,
    districtName: 'Subarnapur',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 132,
    districtName: 'Sukma',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 694,
    districtName: 'Sultanpur',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 453,
    districtName: 'Sundargarh',
    stateName: 'Odisha',
    stateId: 26,
  },
  {
    districtId: 72,
    districtName: 'Supaul',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 133,
    districtName: 'Surajpur',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 165,
    districtName: 'Surat',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 776,
    districtName: 'Surat Corporation',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 157,
    districtName: 'Surendranagar',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 134,
    districtName: 'Surguja',
    stateName: 'Chhattisgarh',
    stateId: 7,
  },
  {
    districtId: 606,
    districtName: 'Suryapet',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 404,
    districtName: 'Tamenglong',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 166,
    districtName: 'Tapi',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 495,
    districtName: 'Tarn Taran',
    stateName: 'Punjab',
    stateId: 28,
  },
  {
    districtId: 30,
    districtName: 'Tawang',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 701,
    districtName: 'Tehri Garhwal',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 407,
    districtName: 'Tengnoupal',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 551,
    districtName: 'Tenkasi',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 392,
    districtName: 'Thane',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 541,
    districtName: 'Thanjavur',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 569,
    districtName: 'Theni',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 296,
    districtName: 'Thiruvananthapuram',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 554,
    districtName: 'Thoothukudi (Tuticorin)',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 405,
    districtName: 'Thoubal',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 303,
    districtName: 'Thrissur',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 325,
    districtName: 'Tikamgarh',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 45,
    districtName: 'Tinsukia',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 26,
    districtName: 'Tirap',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 560,
    districtName: 'Tiruchirappalli',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 548,
    districtName: 'Tirunelveli',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 550,
    districtName: 'Tirupattur',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 568,
    districtName: 'Tiruppur',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 572,
    districtName: 'Tiruvallur',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 553,
    districtName: 'Tiruvannamalai',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 574,
    districtName: 'Tiruvarur',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 526,
    districtName: 'Tonk',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 440,
    districtName: 'Tuensang',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 288,
    districtName: 'Tumkur',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 504,
    districtName: 'Udaipur',
    stateName: 'Rajasthan',
    stateId: 29,
  },
  {
    districtId: 65,
    districtName: 'Udalguri',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 705,
    districtName: 'Udham Singh Nagar',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 233,
    districtName: 'Udhampur',
    stateName: 'Jammu and Kashmir',
    stateId: 14,
  },
  {
    districtId: 286,
    districtName: 'Udupi',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 318,
    districtName: 'Ujjain',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 406,
    districtName: 'Ukhrul',
    stateName: 'Manipur',
    stateId: 22,
  },
  {
    districtId: 329,
    districtName: 'Umaria',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 218,
    districtName: 'Una',
    stateName: 'Himachal Pradesh',
    stateId: 13,
  },
  {
    districtId: 620,
    districtName: 'Unakoti',
    stateName: 'Tripura',
    stateId: 33,
  },
  {
    districtId: 695,
    districtName: 'Unnao',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 34,
    districtName: 'Upper Siang',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 41,
    districtName: 'Upper Subansiri',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 736,
    districtName: 'Uttar Dinajpur',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 281,
    districtName: 'Uttar Kannada',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 703,
    districtName: 'Uttarkashi',
    stateName: 'Uttarakhand',
    stateId: 35,
  },
  {
    districtId: 155,
    districtName: 'Vadodara',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 777,
    districtName: 'Vadodara Corporation',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 89,
    districtName: 'Vaishali',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 167,
    districtName: 'Valsad',
    stateName: 'Gujarat',
    stateId: 11,
  },
  {
    districtId: 696,
    districtName: 'Varanasi',
    stateName: 'Uttar Pradesh',
    stateId: 34,
  },
  {
    districtId: 543,
    districtName: 'Vellore',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 355,
    districtName: 'Vidisha',
    stateName: 'Madhya Pradesh',
    stateId: 20,
  },
  {
    districtId: 293,
    districtName: 'Vijayapura',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 607,
    districtName: 'Vikarabad',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 542,
    districtName: 'Viluppuram',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 549,
    districtName: 'Virudhunagar',
    stateName: 'Tamil Nadu',
    stateId: 31,
  },
  {
    districtId: 8,
    districtName: 'Visakhapatnam',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 15,
    districtName: 'Vizianagaram',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 608,
    districtName: 'Wanaparthy',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 609,
    districtName: 'Warangal(Rural)',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 610,
    districtName: 'Warangal(Urban)',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 377,
    districtName: 'Wardha',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 369,
    districtName: 'Washim',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 299,
    districtName: 'Wayanad',
    stateName: 'Kerala',
    stateId: 17,
  },
  {
    districtId: 737,
    districtName: 'West Bardhaman',
    stateName: 'West Bengal',
    stateId: 36,
  },
  {
    districtId: 106,
    districtName: 'West Champaran',
    stateName: 'Bihar',
    stateId: 5,
  },
  {
    districtId: 142,
    districtName: 'West Delhi',
    stateName: 'Delhi',
    stateId: 9,
  },
  {
    districtId: 420,
    districtName: 'West Garo Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 16,
    districtName: 'West Godavari',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 416,
    districtName: 'West Jaintia Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 28,
    districtName: 'West Kameng',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 769,
    districtName: 'West Karbi Anglong',
    stateName: 'Assam',
    stateId: 4,
  },
  {
    districtId: 419,
    districtName: 'West Khasi Hills',
    stateName: 'Meghalaya',
    stateId: 23,
  },
  {
    districtId: 38,
    districtName: 'West Siang',
    stateName: 'Arunachal Pradesh',
    stateId: 3,
  },
  {
    districtId: 536,
    districtName: 'West Sikkim',
    stateName: 'Sikkim',
    stateId: 30,
  },
  {
    districtId: 263,
    districtName: 'West Singhbhum',
    stateName: 'Jharkhand',
    stateId: 15,
  },
  {
    districtId: 621,
    districtName: 'West Tripura',
    stateName: 'Tripura',
    stateId: 33,
  },
  {
    districtId: 436,
    districtName: 'Wokha',
    stateName: 'Nagaland',
    stateId: 25,
  },
  {
    districtId: 611,
    districtName: 'Yadadri Bhuvanagiri',
    stateName: 'Telangana',
    stateId: 32,
  },
  {
    districtId: 285,
    districtName: 'Yadgir',
    stateName: 'Karnataka',
    stateId: 16,
  },
  {
    districtId: 197,
    districtName: 'Yamunanagar',
    stateName: 'Haryana',
    stateId: 12,
  },
  {
    districtId: 478,
    districtName: 'Yanam',
    stateName: 'Puducherry',
    stateId: 27,
  },
  {
    districtId: 368,
    districtName: 'Yavatmal',
    stateName: 'Maharashtra',
    stateId: 21,
  },
  {
    districtId: 6,
    districtName: 'YSR District, Kadapa (Cuddapah)',
    stateName: 'Andhra Pradesh',
    stateId: 2,
  },
  {
    districtId: 442,
    districtName: 'Zunheboto',
    stateName: 'Nagaland',
    stateId: 25,
  },
];

export default districts;

/*
function getFreshDistricts() {
  const districts = []
  for (let s in states) {
    const res = await axios({
      method: 'get',
      url: `admin/location/districts/${states[s]}`
    })
    const ds = resddata['districts']
    for (let d of ds) {
      d['stateName'] = s;
      d['stateId'] = states[s];
      districts.push(d)
    }
  }
  districts.sort((d1, d2) => d1['districtName'].localeCompare(d2['districtName']))
  console.log(districts)
}
*/
